In [1]:
# Import basic packages

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataset=pd.read_csv('M4_Diabetes.csv')

In [3]:
dataset

No.of_times_pregnant  glucose_conc  blood_pressure  skin_fold_thickness  \
0                        6           148              72                   35   
1                        1            85              66                   29   
2                        8           183              64                    0   
3                        1            89              66                   23   
4                        0           137              40                   35   
..                     ...           ...             ...                  ...   
763                     10           101              76                   48   
764                      2           122              70                   27   
765                      5           121              72                   23   
766                      1           126              60                    0   
767                      1            93              70                   31   

     2-Hour_serum_insulin   BMI  Diabetes_pedigree_fn  Age Is_Diabetic  
0                       0  33.6                 0.627   50         YES  
1                       0  26.6                 0.351   31          NO  
2                       0  23.3                 0.672   32         YES  
3                      94  28.1                 0.167   21          NO  
4                     168  43.1                 2.288   33         YES  
..                    ...   ...                   ...  ...         ...  
763                   180  32.9                 0.171   63          NO  
764                     0  36.8                 0.340   27          NO  
765                   112  26.2                 0.245   30          NO  
766                     0  30.1                 0.349   47         YES  
767                     0  30.4                 0.315   23          NO  

[768 rows x 9 columns]

# Data Preprocessing


#### Missing Values


In [12]:
dataset['blood_pressure'].value_counts()

72.0     79
70.0     57
74.0     52
78.0     45
68.0     45
64.0     43
80.0     40
76.0     39
60.0     37
62.0     34
82.0     30
66.0     30
88.0     25
84.0     23
90.0     22
58.0     21
86.0     21
50.0     13
56.0     12
54.0     11
52.0     11
92.0      8
75.0      8
65.0      7
94.0      6
85.0      6
48.0      5
96.0      4
44.0      4
110.0     3
106.0     3
98.0      3
100.0     3
108.0     2
55.0      2
30.0      2
104.0     2
46.0      2
122.0     1
95.0      1
102.0     1
61.0      1
40.0      1
24.0      1
38.0      1
114.0     1
Name: blood_pressure, dtype: int64

In [4]:
dataset.isnull().sum()

 No.of_times_pregnant    0
glucose_conc             0
blood_pressure           0
skin_fold_thickness      0
2-Hour_serum_insulin     0
BMI                      0
Diabetes_pedigree_fn     0
Age                      0
Is_Diabetic              0
dtype: int64

No missing data

In [5]:
dataset.describe()

No.of_times_pregnant  glucose_conc  blood_pressure  \
count             768.000000    768.000000      768.000000   
mean                3.845052    120.894531       69.105469   
std                 3.369578     31.972618       19.355807   
min                 0.000000      0.000000        0.000000   
25%                 1.000000     99.000000       62.000000   
50%                 3.000000    117.000000       72.000000   
75%                 6.000000    140.250000       80.000000   
max                17.000000    199.000000      122.000000   

       skin_fold_thickness  2-Hour_serum_insulin         BMI  \
count           768.000000            768.000000  768.000000   
mean             20.536458             79.799479   31.992578   
std              15.952218            115.244002    7.884160   
min               0.000000              0.000000    0.000000   
25%               0.000000              0.000000   27.300000   
50%              23.000000             30.500000   32.000000   
75%              32.000000            127.250000   36.600000   
max              99.000000            846.000000   67.100000   

       Diabetes_pedigree_fn         Age  
count            768.000000  768.000000  
mean               0.471876   33.240885  
std                0.331329   11.760232  
min                0.078000   21.000000  
25%                0.243750   24.000000  
50%                0.372500   29.000000  
75%                0.626250   41.000000  
max                2.420000   81.000000

Here from the data we can observe that for multiple columns like blood_pressure,BMI etc the min value is 0 which is not possible in reality.So we have to replace the 0 value with mean/median

In [6]:
dataset['glucose_conc']=np.where(dataset['glucose_conc']==0,dataset['glucose_conc'].median(),dataset['glucose_conc'])

In [7]:
dataset['blood_pressure']=np.where(dataset['blood_pressure']==0,dataset['blood_pressure'].median(),dataset['blood_pressure'])

In [8]:
dataset['skin_fold_thickness']=np.where(dataset['skin_fold_thickness']==0,dataset['skin_fold_thickness'].median(),dataset['skin_fold_thickness'])

In [9]:
dataset['2-Hour_serum_insulin']=np.where(dataset['2-Hour_serum_insulin']==0,dataset['2-Hour_serum_insulin'].median(),dataset['2-Hour_serum_insulin'])

In [10]:
dataset['BMI']=np.where(dataset['BMI']==0,dataset['BMI'].median(),dataset['BMI'])

In [11]:
dataset.describe()

No.of_times_pregnant  glucose_conc  blood_pressure  \
count             768.000000    768.000000      768.000000   
mean                3.845052    121.656250       72.386719   
std                 3.369578     30.438286       12.096642   
min                 0.000000     44.000000       24.000000   
25%                 1.000000     99.750000       64.000000   
50%                 3.000000    117.000000       72.000000   
75%                 6.000000    140.250000       80.000000   
max                17.000000    199.000000      122.000000   

       skin_fold_thickness  2-Hour_serum_insulin         BMI  \
count           768.000000            768.000000  768.000000   
mean             27.334635             94.652344   32.450911   
std               9.229014            105.547598    6.875366   
min               7.000000             14.000000   18.200000   
25%              23.000000             30.500000   27.500000   
50%              23.000000             31.250000   32.000000   
75%              32.000000            127.250000   36.600000   
max              99.000000            846.000000   67.100000   

       Diabetes_pedigree_fn         Age  
count            768.000000  768.000000  
mean               0.471876   33.240885  
std                0.331329   11.760232  
min                0.078000   21.000000  
25%                0.243750   24.000000  
50%                0.372500   29.000000  
75%                0.626250   41.000000  
max                2.420000   81.000000

In [13]:
dataset.head()

No.of_times_pregnant  glucose_conc  blood_pressure  skin_fold_thickness  \
0                      6         148.0            72.0                 35.0   
1                      1          85.0            66.0                 29.0   
2                      8         183.0            64.0                 23.0   
3                      1          89.0            66.0                 23.0   
4                      0         137.0            40.0                 35.0   

   2-Hour_serum_insulin   BMI  Diabetes_pedigree_fn  Age Is_Diabetic  
0                  30.5  33.6                 0.627   50         YES  
1                  30.5  26.6                 0.351   31          NO  
2                  30.5  23.3                 0.672   32         YES  
3                  94.0  28.1                 0.167   21          NO  
4                 168.0  43.1                 2.288   33         YES

#### Label Encoding

In [14]:
dataset['Is_Diabetic']=dataset['Is_Diabetic'].astype('category')
dataset['Is_Diabetic']=dataset['Is_Diabetic'].cat.codes
dataset=pd.get_dummies(dataset,columns=['Is_Diabetic'])

In [15]:
dataset.head()

No.of_times_pregnant  glucose_conc  blood_pressure  skin_fold_thickness  \
0                      6         148.0            72.0                 35.0   
1                      1          85.0            66.0                 29.0   
2                      8         183.0            64.0                 23.0   
3                      1          89.0            66.0                 23.0   
4                      0         137.0            40.0                 35.0   

   2-Hour_serum_insulin   BMI  Diabetes_pedigree_fn  Age  Is_Diabetic_0  \
0                  30.5  33.6                 0.627   50              0   
1                  30.5  26.6                 0.351   31              1   
2                  30.5  23.3                 0.672   32              0   
3                  94.0  28.1                 0.167   21              1   
4                 168.0  43.1                 2.288   33              0   

   Is_Diabetic_1  
0              1  
1              0  
2              1  
3              0  
4              1

In [16]:
dataset=dataset.drop(['Is_Diabetic_0'],axis=1)

In [17]:
dataset.head()

No.of_times_pregnant  glucose_conc  blood_pressure  skin_fold_thickness  \
0                      6         148.0            72.0                 35.0   
1                      1          85.0            66.0                 29.0   
2                      8         183.0            64.0                 23.0   
3                      1          89.0            66.0                 23.0   
4                      0         137.0            40.0                 35.0   

   2-Hour_serum_insulin   BMI  Diabetes_pedigree_fn  Age  Is_Diabetic_1  
0                  30.5  33.6                 0.627   50              1  
1                  30.5  26.6                 0.351   31              0  
2                  30.5  23.3                 0.672   32              1  
3                  94.0  28.1                 0.167   21              0  
4                 168.0  43.1                 2.288   33              1

#### Check Balanced Data

In [18]:
dataset['Is_Diabetic_1'].value_counts()

0    500
1    268
Name: Is_Diabetic_1, dtype: int64

In [19]:
# Split the data into independent & depedent variables
x=dataset.iloc[:,:-1]
y=dataset['Is_Diabetic_1']

In [20]:
x

No.of_times_pregnant  glucose_conc  blood_pressure  skin_fold_thickness  \
0                        6         148.0            72.0                 35.0   
1                        1          85.0            66.0                 29.0   
2                        8         183.0            64.0                 23.0   
3                        1          89.0            66.0                 23.0   
4                        0         137.0            40.0                 35.0   
..                     ...           ...             ...                  ...   
763                     10         101.0            76.0                 48.0   
764                      2         122.0            70.0                 27.0   
765                      5         121.0            72.0                 23.0   
766                      1         126.0            60.0                 23.0   
767                      1          93.0            70.0                 31.0   

     2-Hour_serum_insulin   BMI  Diabetes_pedigree_fn  Age  
0                    30.5  33.6                 0.627   50  
1                    30.5  26.6                 0.351   31  
2                    30.5  23.3                 0.672   32  
3                    94.0  28.1                 0.167   21  
4                   168.0  43.1                 2.288   33  
..                    ...   ...                   ...  ...  
763                 180.0  32.9                 0.171   63  
764                  30.5  36.8                 0.340   27  
765                 112.0  26.2                 0.245   30  
766                  30.5  30.1                 0.349   47  
767                  30.5  30.4                 0.315   23  

[768 rows x 8 columns]

In [21]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Is_Diabetic_1, Length: 768, dtype: uint8

# Split the data into training & test for model building & evaluation

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=30)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


# Model 1-Logistic Regression

In [23]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [24]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [25]:
y_pred_lr_train=lr.predict(x_train)
y_pred_lr_test=lr.predict(x_test)

#### Classification Report

In [26]:
print(classification_report(y_train,y_pred_lr_train))
print("*"*80)
print(classification_report(y_test,y_pred_lr_test))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       370
           1       0.73      0.57      0.64       206

    accuracy                           0.77       576
   macro avg       0.76      0.73      0.74       576
weighted avg       0.77      0.77      0.76       576

********************************************************************************
              precision    recall  f1-score   support

           0       0.83      0.88      0.86       130
           1       0.72      0.63      0.67        62

    accuracy                           0.80       192
   macro avg       0.78      0.76      0.77       192
weighted avg       0.80      0.80      0.80       192



#### Confusion matrix

In [27]:
print(confusion_matrix(y_train,y_pred_lr_train))
print("*"*30)
print(confusion_matrix(y_test,y_pred_lr_test))

[[327  43]
 [ 89 117]]
******************************
[[115  15]
 [ 23  39]]


#### Accuracy score

In [28]:
print(accuracy_score(y_train,y_pred_lr_train))
print("*"*20)
print(accuracy_score(y_test,y_pred_lr_test))

0.7708333333333334
********************
0.8020833333333334


# Model 2- Decision Tree

In [29]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [30]:
y_pred_dt_train=dt.predict(x_train)
y_pred_dt_test=dt.predict(x_test)

#### Classification Report

In [31]:
print(classification_report(y_train,y_pred_dt_train))
print("*"*80)
print(classification_report(y_test,y_pred_dt_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       370
           1       1.00      1.00      1.00       206

    accuracy                           1.00       576
   macro avg       1.00      1.00      1.00       576
weighted avg       1.00      1.00      1.00       576

********************************************************************************
              precision    recall  f1-score   support

           0       0.78      0.76      0.77       130
           1       0.52      0.55      0.54        62

    accuracy                           0.69       192
   macro avg       0.65      0.65      0.65       192
weighted avg       0.70      0.69      0.69       192



#### Confusion matrix

In [32]:
print(confusion_matrix(y_train,y_pred_dt_train))
print("*"*30)
print(confusion_matrix(y_test,y_pred_dt_test))

[[370   0]
 [  0 206]]
******************************
[[99 31]
 [28 34]]


#### Accuracy score

In [33]:
print(accuracy_score(y_train,y_pred_dt_train))
print("*"*20)
print(accuracy_score(y_test,y_pred_dt_test))

1.0
********************
0.6927083333333334


# Model 3- Bagging

In [34]:
#Fit the model

from sklearn.ensemble import BaggingClassifier
bagging=BaggingClassifier()
bagging.fit(x_train,y_train)

BaggingClassifier()

In [35]:
y_pred_bag_train=bagging.predict(x_train)
y_pred_bag_test=bagging.predict(x_test)

#### Classification Report

In [36]:
print(classification_report(y_train,y_pred_bag_train))
print("*"*80)
print(classification_report(y_test,y_pred_bag_test))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       370
           1       1.00      0.98      0.99       206

    accuracy                           0.99       576
   macro avg       0.99      0.99      0.99       576
weighted avg       0.99      0.99      0.99       576

********************************************************************************
              precision    recall  f1-score   support

           0       0.78      0.82      0.80       130
           1       0.57      0.52      0.54        62

    accuracy                           0.72       192
   macro avg       0.68      0.67      0.67       192
weighted avg       0.71      0.72      0.71       192



#### Confusion matrix

In [37]:
print(confusion_matrix(y_train,y_pred_bag_train))
print("*"*30)
print(confusion_matrix(y_test,y_pred_bag_test))

[[370   0]
 [  5 201]]
******************************
[[106  24]
 [ 30  32]]


#### Accuracy score

In [38]:
print(accuracy_score(y_train,y_pred_bag_train))
print("*"*20)
print(accuracy_score(y_test,y_pred_bag_test))

0.9913194444444444
********************
0.71875


# Model 4- Random Forest

In [39]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [40]:
y_pred_rf_train=rf.predict(x_train)
y_pred_rf_test=rf.predict(x_test)

#### Classification Report

In [41]:
print(classification_report(y_train,y_pred_rf_train))
print("*"*80)
print(classification_report(y_test,y_pred_rf_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       370
           1       1.00      1.00      1.00       206

    accuracy                           1.00       576
   macro avg       1.00      1.00      1.00       576
weighted avg       1.00      1.00      1.00       576

********************************************************************************
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       130
           1       0.69      0.65      0.67        62

    accuracy                           0.79       192
   macro avg       0.76      0.75      0.76       192
weighted avg       0.79      0.79      0.79       192



#### Confusion matrix

In [42]:
print(confusion_matrix(y_train,y_pred_rf_train))
print("*"*30)
print(confusion_matrix(y_test,y_pred_rf_test))

[[370   0]
 [  0 206]]
******************************
[[112  18]
 [ 22  40]]


#### Accuracy score

In [43]:
print(accuracy_score(y_train,y_pred_rf_train))
print("*"*20)
print(accuracy_score(y_test,y_pred_rf_test))

1.0
********************
0.7916666666666666


# Cross Validation approach to handle overfitting problem in Random Forest

In [45]:
from sklearn.model_selection import cross_val_score
#acc_training=cross_val_score(rf,x_train,y_train,cv=10)
acc_test=cross_val_score(rf,x_test,y_test,cv=15)
#print(acc_training)
print(acc_test)

[0.92307692 0.69230769 0.84615385 0.61538462 0.84615385 0.76923077
 0.84615385 0.53846154 0.61538462 0.76923077 0.69230769 0.76923077
 0.75       0.66666667 0.91666667]


In [46]:
print(acc_test[0])

0.9230769230769231


# Model 5- Gradient Boosting

In [48]:
from sklearn.ensemble import GradientBoostingClassifier
gdb=GradientBoostingClassifier()
gdb.fit(x_train,y_train)

GradientBoostingClassifier()

In [49]:
y_pred_gdb_train=gdb.predict(x_train)
y_pred_gdb_test=gdb.predict(x_test)

#### Classification Report

In [50]:
print(classification_report(y_train,y_pred_gdb_train))
print("*"*80)
print(classification_report(y_test,y_pred_gdb_test))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95       370
           1       0.93      0.88      0.91       206

    accuracy                           0.93       576
   macro avg       0.93      0.92      0.93       576
weighted avg       0.93      0.93      0.93       576

********************************************************************************
              precision    recall  f1-score   support

           0       0.82      0.85      0.84       130
           1       0.67      0.61      0.64        62

    accuracy                           0.78       192
   macro avg       0.74      0.73      0.74       192
weighted avg       0.77      0.78      0.77       192



#### Confusion matrix

In [51]:
print(confusion_matrix(y_train,y_pred_gdb_train))
print("*"*30)
print(confusion_matrix(y_test,y_pred_gdb_test))

[[357  13]
 [ 25 181]]
******************************
[[111  19]
 [ 24  38]]


#### Accuracy score

In [52]:
print(accuracy_score(y_train,y_pred_gdb_train))
print("*"*20)
print(accuracy_score(y_test,y_pred_gdb_test))

0.9340277777777778
********************
0.7760416666666666


# Model 6- AdaBoosting

In [53]:
from sklearn.ensemble import AdaBoostClassifier
abc=AdaBoostClassifier()
abc.fit(x_train,y_train)

AdaBoostClassifier()

In [54]:
y_pred_abc_train=abc.predict(x_train)
y_pred_abc_test=abc.predict(x_test)

#### Classification Report

In [55]:
print(classification_report(y_train,y_pred_abc_train))
print("*"*80)
print(classification_report(y_test,y_pred_abc_test))

              precision    recall  f1-score   support

           0       0.86      0.88      0.87       370
           1       0.77      0.74      0.75       206

    accuracy                           0.83       576
   macro avg       0.81      0.81      0.81       576
weighted avg       0.83      0.83      0.83       576

********************************************************************************
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       130
           1       0.64      0.61      0.63        62

    accuracy                           0.77       192
   macro avg       0.73      0.73      0.73       192
weighted avg       0.76      0.77      0.76       192



#### Confusion matrix

In [56]:
print(confusion_matrix(y_train,y_pred_abc_train))
print("*"*30)
print(confusion_matrix(y_test,y_pred_abc_test))

[[325  45]
 [ 54 152]]
******************************
[[109  21]
 [ 24  38]]


#### Accuracy score

In [57]:
print(accuracy_score(y_train,y_pred_abc_train))
print("*"*20)
print(accuracy_score(y_test,y_pred_abc_test))

0.828125
********************
0.765625


# Model 7- XGBoosting

In [58]:
pip install xgboost

In [59]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(x_train,y_train)

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:57:42] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [60]:
y_pred_xgb_train=xgb.predict(x_train)
y_pred_xgb_test=xgb.predict(x_test)

#### Classification Report

In [61]:
print(classification_report(y_train,y_pred_xgb_train))
print("*"*80)
print(classification_report(y_test,y_pred_xgb_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       370
           1       1.00      1.00      1.00       206

    accuracy                           1.00       576
   macro avg       1.00      1.00      1.00       576
weighted avg       1.00      1.00      1.00       576

********************************************************************************
              precision    recall  f1-score   support

           0       0.82      0.81      0.81       130
           1       0.61      0.63      0.62        62

    accuracy                           0.75       192
   macro avg       0.71      0.72      0.72       192
weighted avg       0.75      0.75      0.75       192



#### Confusion matrix

In [62]:
print(confusion_matrix(y_train,y_pred_xgb_train))
print("*"*30)
print(confusion_matrix(y_test,y_pred_xgb_test))

[[370   0]
 [  0 206]]
******************************
[[105  25]
 [ 23  39]]


#### Accuracy score

In [63]:
print(accuracy_score(y_train,y_pred_xgb_train))
print("*"*20)
print(accuracy_score(y_test,y_pred_xgb_test))

1.0
********************
0.75


# Model 8- KNN

In [64]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [65]:
y_pred_knn_train=knn.predict(x_train)
y_pred_knn_test=knn.predict(x_test)

#### Classification Report

In [66]:
print(classification_report(y_train,y_pred_knn_train))
print("*"*80)
print(classification_report(y_test,y_pred_knn_test))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85       370
           1       0.74      0.67      0.71       206

    accuracy                           0.80       576
   macro avg       0.78      0.77      0.78       576
weighted avg       0.80      0.80      0.80       576

********************************************************************************
              precision    recall  f1-score   support

           0       0.82      0.76      0.79       130
           1       0.56      0.65      0.60        62

    accuracy                           0.72       192
   macro avg       0.69      0.70      0.70       192
weighted avg       0.74      0.72      0.73       192



#### Confusion matrix

In [67]:
print(confusion_matrix(y_train,y_pred_knn_train))
print("*"*30)
print(confusion_matrix(y_test,y_pred_knn_test))

[[321  49]
 [ 67 139]]
******************************
[[99 31]
 [22 40]]


#### Accuracy score

In [68]:
print(accuracy_score(y_train,y_pred_knn_train))
print("*"*20)
print(accuracy_score(y_test,y_pred_knn_test))

0.7986111111111112
********************
0.7239583333333334
